---
- hosts: compute_nodes
  become: true
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
         update_cache: yes

    - name: Install required build tools
      ansible.builtin.apt:
        name:
          - build-essential
          - autoconf
          - libtool
          - pkg-config
        state: present

    - name: Clone Munge repository
      git:
        repo: "https://github.com/dun/munge.git"
        dest: "/home/billy.nguyen@sentientvision.com/work/Munge"
        version: "master"
        update: yes
      tags: clone

#    - name: Generate configure script (autoreconf)
#      command: autoreconf -i
#      args:
#        chdir: "/home/billy.nguyen@sentientvision.com/work/Munge"

    - name: Configure Munge
      command: ./configure
      args:
        chdir: "/home/billy.nguyen@sentientvision.com/work/Munge"

    - name: Compile Munge (make)
      command: make
      args:
        chdir: "/home/billy.nguyen@sentientvision.com/work/Munge"

    - name: Install Munge (make install)
      command: make install
      args:
        chdir: "/home/billy.nguyen@sentientvision.com/work/Munge"

    - name: Create munge group
      group:
        name: munge
        state: present

    - name: Create munge user
      user:
        name: munge
        group: munge
        home: /var/lib/munge
        shell: /sbin/nologin
        system: yes
        state: present

    - name: Set ownership and permissions on /etc/munge
      file:
        path: /etc/munge
        owner: munge
        group: munge
        mode: '0700'
        recurse: yes

    - name: Ensure /var/log is owned by root and has mode 0755
      file:
        path: /var/log
        owner: root
        group: root
        mode: '0755'

    - name: Create /var/log/munge directory with correct permissions
      file:
        path: /var/log/munge
        state: directory
        owner: munge
        group: munge
        mode: '0750'

    - name: Create /usr/local/var/run with correct permissions
      file:
        path: /usr/local/var/run
        state: directory
        owner: munge
        group: munge
        mode: '0750'

    - name: Create /usr/local/var/run/munge with correct permissions
      file:
        path: /usr/local/var/run/munge
        state: directory
        owner: munge
        group: munge
        mode: '0750'

    - name: Ensure /var/log is owned by root and has mode 0755
      file:
        path: /var/log
        owner: root
        group: root
        mode: '0755'

    - name: Create /var/log/munge directory with correct permissions
      file:
        path: /var/log/munge
        state: directory
        owner: munge
        group: munge
        mode: '0750'

    - name: Update ExecStart in munge systemd unit
      become: true
      ansible.builtin.lineinfile:
        path: /usr/local/lib/systemd/system/munge.service
        regexp: '^ExecStart='
        line: 'ExecStart=/usr/local/sbin/munged --socket=/usr/local/var/run/munge/munge.socket.2'
        backup: yes

    - name: Clone Slurm repository (slurm-24.11 branch)
      git:
        repo: "https://github.com/SchedMD/slurm.git"
        dest: "/home/billy.nguyen@sentientvision.com/work/Slurm"
        version: "slurm-24.11"
        update: yes
      tags: clone

    - name: Configure Slurm
      command: "./configure"
      args:
        chdir: "/home/billy.nguyen@sentientvision.com/work/Slurm"

    - name: Install Slurm (make install)
      command: "make install"
      args:
        chdir: "/home/billy.nguyen@sentientvision.com/work/Slurm"

    - name: Create slurm group
      group:
        name: slurm
        state: present

    - name: Create slurm user
      user:
        name: slurm
        group: slurm
        home: /var/lib/slurm
        shell: /sbin/nologin
        system: yes
        state: present

    - name: Update ExecStart in Slurmd systemd unit
      become: true
      ansible.builtin.lineinfile:
        path: /etc/systemd/system/slurmd.service
        regexp: '^ExecStart='
        line: 'ExecStart=/usr/local/sbin/slurmd --systemd --conf-server BM-Ubuntu24:6817'
        backup: yes

    - name: Reload systemd daemon
      become: true
      ansible.builtin.command:
        cmd: systemctl daemon-reexec

    - name: Enable and start Munge service
      ansible.builtin.systemd:
        name: munge
        enabled: yes
        state: started

    - name: Check Munge service status
      command: systemctl status munge.service
      register: munge_service_status
      ignore_errors: yes

    - name: Display Munge service status output
      debug:
        var: munge_service_status.stdout

    - name: Enable and Start Slurm
      systemd:
        name: slurmd
        enabled: yes
        state: started

    - name: Check Slurm Status
      command: systemctl status slurmd
      register: slurm_service_status
      ignore_errors: yes

    - name: Display slurm service status output
      debug:
        var: slurm_service_status.results
