---
- name: Gather facts only
  hosts: all
  gather_facts: yes
  tasks:
    - name: Just print a message to confirm facts were gathered
      debug:
        msg: "Facts have been gathered for {{ inventory_hostname }}"
