---
- name: Simple test playbook
  hosts: controller_node
  become: yes
  tasks:
    - name: Create a file to test Ansible
      file:
        path: /tmp/ansible_test_file.txt
        state: touch
        mode: '0644'
