---
  - hosts: controller_node
    gather_facts: false
    become: true
    tasks:
      - name: Copy /usr/local/etc/munge/munge.key to home directory
        copy:
          src: /usr/local/etc/munge/munge.key
          dest: /home/bnguyen/munge.key
          mode: '0777'
          remote_src: true

      - name: SCP munge.key to remote server
        ansible.builtin.command: >
          scp -o StrictHostKeyChecking=no
          /home/bnguyen/munge.key
          billy.nguyen@sentientvision.com@192.168.91.107:~/
        register: scp_result
        ignore_errors: yes

  - hosts: controller_node
    gather_facts: false
    become: true
    tasks:
      - name: Remove munge.key from home directory
        file:
          path: /home/bnguyen/munge.key
          state: absent

  - hosts: compute_nodes
    become: true
    tasks:
      - name: Move munge.key to /etc/munge/
        command: mv /home/billy.nguyen@sentientvision.com/munge.key /usr/local/etc/munge/munge.key
        args:
          removes: /home/billy.nguyen@sentientvision.com/munge.key

      - name: Change ownership to munge:munge
        file:
          path: /usr/local/etc/munge/munge.key
          owner: munge
          group: munge

      - name: Set permissions for Munge.key
        file:
          path: /usr/local/etc/munge/munge.key
          mode: '0700'
