---

- hosts: compute_nodes
  become: true
  tasks:

  - name: restart munge
    tags: munge
    service:
       name: munge
       state: restarted

  - name: restart slurm
    tags: slurm
    service:
      name: slurmd
      state: restarted
