---

- hosts: compute_nodes
  become: false
  tasks:

#  - name: restart slurm
#    tags: slurm
#    service:
#      name: slurmd
#      state: restarted

  - name: restart munge
    tags: munge
    service:
       name: munge
       state: restarted
