---
- name: Restart Slurm Controller
  hosts: controller_node
  become: yes
  tasks:
    - name: Ensure Munge is running
      systemd:
        name: munge
        state: restarted
        enabled: yes
