---
- hosts: controller_node
  become: true
  tasks:
    - name: Repository signing key
      shell: |
        sudo curl -sS https://pkgs.rackslab.io/keyring.asc | gpg --dearmor | sudo tee /usr/share/keyrings/rackslab.gpg > /dev/null

- hosts: controller_node
  become: yes
  tasks:
    - name: Create APT sources file
      ansible.builtin.copy:
        dest: "/etc/apt/sources.list.d/rackslab.sources"
        content: |
          Types: deb
          URIs: https://pkgs.rackslab.io/deb
          Suites: ubuntu24.04
          Components: main
          Architectures: amd64
          Signed-By: /usr/share/keyrings/rackslab.gpg
        mode: '0644'

- hosts: controller_node
  become: true
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes


    - name: Install Slurm-web, Racksdb and dependencies
      ansible.builtin.apt:
        name:
          - racksdb
          - libcairo2-dev
          - libgirepository1.0-dev

        state: present

- hosts: controller_node
  become: true
  tasks:
    - name: Install SlurmRest package using dpkg
      command: sudo dpkg -i /home/bnguyen/Work/SlurmRest/slurmrestd_24.11.1-1_amd64.deb
      args:
        chdir: /home/bnguyen/Work/SlurmRest
      register: dpkg_install
      ignore_errors: yes

    - name: Fix missing dependencies
      ansible.builtin.apt:
        name: "*"
        state: latest
        force_apt_get: yes
      when: dpkg_install.failed


- hosts: controller_node
  become: yes
  tasks:
    - name: Create Slurmrest Config file
      ansible.builtin.copy:
        dest: "/etc/systemd/system/slurmrestd.service.d/slurm-web.conf"
        content: |
          [Service]
          # Unset vendor unit ExecStart to avoid cumulative definition
          ExecStart=
          Environment=
          # Disable slurm user security check
          Environment=SLURMRESTD_SECURITY=disable_user_check
          ExecStart=/usr/local/sbin/slurmrestd $SLURMRESTD_OPTIONS unix:/run/slurmrestd/slurmrestd.socket
          RuntimeDirectory=slurmrestd
          RuntimeDirectoryMode=0755
          User=slurm-web
          Group=slurm-web
        mode: '0644'

- hosts: controller_node
  become: yes
  tasks:
    - name: Install Slurm-Web-Agent and Slurm-Web-Gateway
      ansible.builtin.apt:
        name:
          - slurm-web-agent
          - slurm-web-gateway
        state: present

    - name: Create directory /etc/slurm-web
      ansible.builtin.file:
        path: /etc/slurm-web
        state: directory
        mode: '0755'

- hosts: controller_node
  become: yes
  tasks:
    - name: Create Slurm-web-agent configuration file
      ansible.builtin.copy:
        dest: "/etc/slurm-web/agent.ini"
        content: |
          [service]
          cluster=cluster

          [metrics]
          enabled=yes

          [racksdb]

          # Path to RacksDB database
          #
          # Default value: /var/lib/racksdb
          db=/var/lib/racksdb

          # Path to RacksDB database schema
          #
          # Default value: /usr/share/racksdb/schemas/racksdb.yml
          schema=/usr/share/racksdb/schemas/racksdb.yml

          # Path to site-specific RacksDB schema extensions
          #
          # Default value: /etc/racksdb/extensions.yml
          extensions=/etc/racksdb/extensions.yml

          # Path to RacksDB database schema
          #
          # Default value: /usr/share/racksdb/schemas/drawings.yml
          drawings_schema=/usr/share/racksdb/schemas/drawings.yml

          # Name of the infrastructure for the cluster in RacksDB. By default, the
          # cluster name is used.
          infrastructure=cluster

          # List of tags applied to compute nodes in RacksDB database
          #
          # Default value:
          # - compute
          tags=
            compute
        mode: '0644'

- hosts: controller_node
  become: yes
  tasks:
    - name: Create Slurm-web-gateway configuration file
      ansible.builtin.copy:
        dest: "/etc/slurm-web/gateway.ini"
        content: |
          [agents]
          url=http://localhost:5012
        mode: '0644'

    - name: Create directory /var/lib/slurm
      ansible.builtin.file:
        path: /var/lib/slurm-web
        state: directory
        mode: '0755'

    - name: Generate JWT key for Slurm web API
      command: sudo /usr/libexec/slurm-web/slurm-web-gen-jwt-key
      args:
        creates: /var/lib/slurm/slurm-web.jwks
      register: jwt_key_output

    - name: Set correct ownership for JWT key
      file:
        path: /var/lib/slurm-web/jwt.key
        owner: slurm
        group: slurm-web
        mode: '0440'
      when: jwt_key_output.changed

- hosts: controller_node
  become: true
  tasks:
    - name: Enable and start Slurm-web services
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - slurmrestd
        - slurm-web-agent
        - slurm-web-gateway

    - name: Check Slurm-web services status
      command: systemctl status "{{ item }}"
      register: slurm_service_status
      ignore_errors: yes
      loop:
        - slurmrestd
        - slurm-web-agent
        - slurm-web-gateway

    - name: Display Slurm services status output
      debug:
        var: slurm_service_status.results

